package project;

/**
 * Represents the aerodynamics part of a car, which affects downforce, drag, and weight.
 */
public class PartAero {
    /**
     * The amount of downforce generated by the car's aerodynamics.
     */
    static int downForce;
    /**
     * The amount of air resistance (drag) generated by the car's aerodynamics.
     */
    int drag;
    /**
     * The weight of the car's aerodynamics.
     */
    int weight;

    /**
     * Constructor for PartAero objects.
     * @param df The amount of downforce generated by the car's aerodynamics.
     * @param drg The amount of air resistance (drag) generated by the car's aerodynamics.
     * @param w The weight of the car's aerodynamics.
     */
    public PartAero(int df, int drg, int w){
        downForce = df;
        drag = drg;
        weight = w;
    }

    /**
     * Sets the amount of downforce generated by the car's aerodynamics.
     * @param downForce The new amount of downforce.
     */
    public void setDownForce(int downForce) {
        this.downForce = downForce;
    }

    /**
     * Sets the amount of air resistance (drag) generated by the car's aerodynamics.
     * @param drag The new amount of drag.
     */
    public void setDrag(int drag) {
        this.drag = drag;
    }

    /**
     * Sets the weight of the car's aerodynamics.
     * @param weight The new weight.
     */
    public void setWeight(int weight) {
        this.weight = weight;
    }

    /**
     * Returns the current amount of downforce generated by the car's aerodynamics.
     * @return The amount of downforce.
     */
    public static int getDownForce() {
        return downForce;
    }

    /**
     * Returns the current amount of air resistance (drag) generated by the car's aerodynamics.
     * @return The amount of drag.
     */
    public int getDrag() {
        return drag;
    }

    /**
     * Returns the current weight of the car's aerodynamics.
     * @return The weight.
     */
    public int getWeight() {
        return weight;
    }
}
